### ISSUE TITLE
온라인 주문서의 통계수집

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Cron-Visitor#1]
https://github.com/opencloset/opencloset/issues/1224

온라인 주문서에서 예약/방문/미방문/bestfit 은 의미가 없습니다.
일일 대여수만 수집하면 될 것 같습니다.

결제일을 저장하고 있지 않기 때문에 시기를 어떻게 저장하는가도 중요합니다.
3월에 주문+결제 하고 4월에 대여할 수 있기 때문입니다.

**Comment by aanoaa** [comment]
오프라인의 경우 예약일을 기준으로 집계하고 있습니다.
온라인은 예약일을 사용하지 않습니다.

- 발송(예정)일
- 대여일
- 도착(예정)일
- 반납희망일
- 반납일

이 중에 가장 어울리는 항목은 대여일이 아닐까 합니다.
iamport 와 데이터의 동기화를 맞추려면 주문서 기준으로 통계를 내면 아니되고,
payment 혹은 payment_log 로 통계를 내야 할 것입니다.

**Comment by aanoaa** [comment]
> iamport 와 데이터의 동기화를 맞추려면 주문서 기준으로 통계를 내면 아니되고,
> payment 혹은 payment_log 로 통계를 내야 할 것입니다.

이것에 대한 의견을 듣고 싶습니다.
@keedi, @yongin, @10001if

**Comment by 10001if** [comment]
@aanoaa 주문서보단느 결제이슈에 따라 정리하는 것이 정확할 것 같습니다.

**Comment by aanoaa** [comment]
아래 스크립트를 실행시켜서 어제까지의 온라인 통계를 수집했습니다.
정확하게는 2017-03-01일 부터가 아니라 2017-03-03일 부터 입니다.

``` perl
use utf8;
use strict;
use warnings;

use DateTime;
use Getopt::Long;
use Pod::Usage;

use OpenCloset::Config;
use OpenCloset::Schema;
use OpenCloset::Cron::Visitor qw/visitor_count_online/;

binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

my %options;
GetOptions( \%options, '--help' );
run( \%options, @ARGV );

sub run {
    my ( $opts, @args ) = @_;
    pod2usage(0) if $opts->{help};

    my $conf    = OpenCloset::Config::load('../opencloset/app.conf');
    my $db_conf = $conf->{database};
    my $schema  = OpenCloset::Schema->connect(
        {
            dsn      => $db_conf->{dsn},
            user     => $db_conf->{user},
            password => $db_conf->{pass},
            %{ $db_conf->{opts} },
        }
    );

    my $tz = $conf->{timezone} || 'Asia/Seoul';
    my $today = DateTime->today( time_zone => $tz );
    my $start_dt = DateTime->new(
        year      => 2017,
        month     => 03,
        day       => 01,
        time_zone => $tz
    );
    my $end_dt = $today->clone->subtract( days => 1 );
    my $dt = $start_dt->clone;

    while ( $dt <= $end_dt ) {
        my $count = visitor_count_online( $schema, $dt );
        $schema->resultset('Visitor')->create(
            {
                date   => "$dt",
                online => 1,

                rented        => $count->{male}{rented} + $count->{female}{rented},
                rented_male   => $count->{male}{rented},
                rented_female => $count->{female}{rented},
            }
        );

        $dt->add( days => 1 );
    }
}
```

**Comment by aanoaa** [comment]
온라인 주문서중에 일괄로 잘못들어간 `rental_date` 를 NULL 로 바꿔주는 스크립트 혹은 쿼리가 필요합니다.

**Comment by aanoaa** [comment]
환불 주문서를 고려해야 합니다.
환불은 결제가 되었던 주문서이기 때문에 `rental_date` 가 있습니다.

- 의류선택
- 주소선택
- 입금대기
- 결제대기

상태의 주문서들은 결제가 되기 전 입니다.
온라인 주문서중에 `rental_date` 가 존재하면서 상태중 하나에 속한다면,
`rental_date` 를 NULL 로 바꾸면 될 것 같습니다.

**Comment by aanoaa** [comment]
``` sql
UPDATE `order` SET rental_date = NULL WHERE online = 1 AND rental_date IS NOT NULL AND rental_date > '2017-03-02' AND status_id IN (48, 49, 56, 19);
```

**Comment by aanoaa** [comment]
잘못된 데이터를 고쳐주고 나니까 지난 3,4월의 통계가 이해할 수 있는 값이 되었습니다.

**Comment by aanoaa** [comment]
환불을 고려한다면 통계 수집방법도 바뀌어야 합니다.

오늘 결제 해서 통계가 수집된 후에 다음날 환불하면?
-> 전날 통계가 이미 수집되었기 때문에 수치가 다를 수 있습니다.

**Comment by aanoaa** [comment]
환불의 변수를 고려치 않고 통계를 수집하도록 하겠습니다.

**Comment by aanoaa** [comment]
[OpenCloset-Cron-Visitor-v0.0.3.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Cron-Visitor-v0.0.3.tar.gz) 배포하였습니다.

**Comment by aanoaa** [comment]
서버에서 아래 쿼리를 실행하였습니다.

```
mysql> UPDATE `order` SET rental_date = NULL WHERE online = 1 AND rental_date IS NOT NULL AND rental_date > '2017-03-02' AND status_id IN (48, 49, 56, 19);
Query OK, 190 rows affected (0.01 sec)
```

**Comment by aanoaa** [comment]
위의 스크립트를 실행해서 2017-03-03 ~ 어제까지의 온라인 통계를 수집하였습니다.
OpenCloset-Cron-Visitor-v0.0.3.tar.gz 를 설치하고 서비스를 재시작 해주었습니다.

    $ ubic restart opencloset.cron.visitor
    Restarting opencloset.cron.visitor... restarted

이제 온라인 통계도 하루치씩 수집하게 됩니다.
