### ISSUE TITLE
광주시 쿠폰 통계 오류

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Cron-Visitor#16]
https://github.com/opencloset/opencloset/issues/1482

통계가 제대로 수집되지 않는다고 합니다.
실제로 0건인지 제대로 동작하지 않는 건지 파악해야 합니다.

**Comment by aanoaa** [comment]
누락된 통계를 수집하는 스크립트는 아래 링크를 참고합니다.
https://github.com/opencloset/opencloset/issues/1412#issuecomment-367580410

**Comment by aanoaa** [comment]
linkstart 의 통계는 2018-04-30 에 마지막으로 수집되었습니다.

**Comment by aanoaa** [comment]
로그 모니터링을 좀 더 수월하게 하는 방안이 필요할 것 같습니다.
(docker 로 작업해놨는데 적용을 못해서..)

**Comment by aanoaa** [comment]
실제로 사용된 쿠폰이 없는 것 같습니다.
예약은 한건 된 것 같은데..

    +---------------+----------+---------------------+
    | desc          | status   | update_date         |
    +---------------+----------+---------------------+
    | gwangju201801 | reserved | 2018-09-03 17:06:12 |
    | gwangju201801 | used     | 2018-08-29 16:16:29 |
    | gwangju201801 | used     | 2018-08-26 10:17:35 |
    | gwangju201801 | reserved | 2018-08-24 21:30:52 |
    | gwangju201801 | used     | 2018-08-23 11:34:42 |
    | gwangju201801 | reserved | 2018-08-10 16:31:43 |
    | gwangju201801 | used     | 2018-07-17 11:43:13 |
    | gwangju201801 | used     | 2018-07-16 10:30:53 |
    | gwangju201801 | used     | 2018-07-13 10:42:38 |
    | gwangju201801 | used     | 2018-07-12 12:21:09 |
    +---------------+----------+---------------------+

**Comment by pingpongworks** [comment]
네~ 0건 맞습니다.ㅜㅜ

**Comment by pingpongworks** [comment]
이슈 닫을게요,,,,ㅜㅜ
